### ISSUE TITLE
Compile errors on DMD 2.072.0-b2 (breaks DDOX and DUB's test suite)

### ISSUE THREAD

**Issue by s-ludwig** [dlang-community/libdparse#112]
Looks like the only thing necessary would be to make a patch release with the experimental_allocator dependency removed  (DDOX uses 0.6.0, so 0.6.1 would be great, but if the 0.7.0 alpha series is reasonably stable, I could also upgrade to that).

**Comment by Hackerpilot** [comment]
I think that I'm going to make a beta for 0.7 once I fix the issue identified here: https://github.com/dlang/phobos/pull/4850

**Comment by MartinNowak** [comment]
Maybe we should just update experimental_allocator with some `static if (__VERSION__ < 207x)` to remain backward compatible?

**Comment by s-ludwig** [comment]
That would be the cleanest solution. But considering that libdparse isn't tested on older DMD versions anyway, I figured that just removing the dependency would be the easier solution.

**Comment by MartinNowak** [comment]
Should be resolved now.
