### ISSUE TITLE
visitIfNotNull for const array

### ISSUE THREAD

**Issue by ANtlord** [dlang-community/libdparse#115]
Hello! During investagiting the [issue](https://github.com/Hackerpilot/dsymbol/issues/14) from project Dsymbol. I've found method `visitIfNotNull` which generates a visitor for an object of child class of class `ASTNode`. It seems this method works unexpectly for `ArrayInitializer`. Take a look [here](https://github.com/Hackerpilot/libdparse/blob/master/src/dparse/ast.d#L353). When it works for `ArrayInitializer` [here](https://github.com/Hackerpilot/libdparse/blob/master/src/dparse/ast.d#L580) this condition is false because type of `fields[0]` is `const(ArrayInitializer[])`. Is it expectly or no? I'm not sure beacuse it doesn't fix my related issue.

If this bug. Should variable be `indexExpression` is null [https://github.com/Hackerpilot/libdparse/blob/master/src/dparse/ast.d#L3195](here)?

**Comment by Hackerpilot** [comment]
I added
```d
pragma(msg, typeof(fields[0]).stringof);
```
to the `visitIfNotNull` template and I didn't see any output that started with `const`. I'm using 2.072.0. Do you see different output?

**Comment by ANtlord** [comment]
I added
```d
writeln(typeof(arrayMemberInitializations));
```
Before this [line](https://github.com/Hackerpilot/libdparse/blob/master/src/dparse/ast.d#L575. But I tested on dmd 2.071.2

**Comment by Hackerpilot** [comment]
The code generation is determined by what the `typeof(thing.stringof)` evaluates to inside of the template, so unless that's incorrect I don't think this is a problem.

**Comment by ANtlord** [comment]
Sorry, I've added stringof too. I mean this:
```d
writeln(typeof(arrayMemberInitializations).stringof);
```
And output is
```
const(ArrayMemberInitialization[])
```

**Comment by BBasile** [comment]
@ANtlord, i think this issue can be closed now, right ? ArrayInitialize is visited correctly since it's now used to solve the type of the most basic auto arrays.

**Comment by ANtlord** [comment]
Sure!
