### ISSUE TITLE
Test suite for the formatter

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/libdparse#129]
> I couldn't find a place for tests of the formatter. A good start for a test suite would be to parse, and dump a lot of D code with high coverage (e.g. parts of Phobos or Mir) - if afterwards all tests still pass, the formatter didn't totally screw up...

**Comment by BBasile** [comment]
I've added something related [here](https://github.com/dlang-community/libdparse/pull/159/files#diff-2343545d81d5046987fe1e0d87461109R3908)

**Comment by WebFreak001** [comment]
was fixed in #159
