### ISSUE TITLE
Token get visited even if empty

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [dlang-community/libdparse#133]
I had the following code:

```D
module pragmamsg;

pragma(msg, int);

void main () {}
```

Running a visitor on this `ModuleDeclaration` that had the following override: `public override void visit (const DParse.Token d) { assert(0); }`, I got it triggered.

The backtrace includes:
```
./submodules/libdparse/src/dparse/ast.d:2175 const(void function(dparse.ast.ASTVisitor)) dparse.ast.Module.accept [0x803524]
```

Which is [here](https://github.com/Hackerpilot/libdparse/blob/v0.7.0-beta.3/src/dparse/ast.d#L2175).
Since the only `Token` in `ModuleDeclaration` is `scriptLine`, I assume that's what get visited.
IMO that shouldn't be the case, as there is no `scriptLine` in said code.

So far I'm working around this by checking `assert(d is Token.init);`.

**Comment by BBasile** [comment]
The fix looks obvious, maybe too. Is there any problem to add this

```d
static if (is(Unqual!(typeof(fields[0] == Token))
{
    if (fields[0] != tok!"")
        immutable visitIfNotNull = "visitor.visit(" ~ fields[0].stringof ~ ");\n";
}
```

 in `visitIfNotNull` ?

I'm also surprised that visit for Token is ever used. I don't think there's a single usage of this in D-Scanner for example.
