### ISSUE TITLE
Parser bug with assoc-array literal

### ISSUE THREAD

**Issue by pirocks** [dlang-community/libdparse#156]
The readme states that static array initialization syntax is unsupported, the following does not appear to be the same as the linked example, and when parsed, gives parse errors:

` string[uint[3]] aa1 = [[1,2,3]: "onetwothree"];  `

**Comment by BBasile** [comment]
The array literal causes the bug to happen.

**Comment by Hackerpilot** [comment]
The array/assoc array parsing code is one of the uglier parts of the parser.

**Comment by BBasile** [comment]
Will you fix it ? I've took a look yesterday and the wrong code / missing code wasn't obvious at all to my eyes (meaning i'm no very motivated to do it).

**Comment by Hackerpilot** [comment]
The first thing to check is the `isAssociativeArrayLiteral` function. The solution may be to get rid of that function and try to parse everything as an associative array literal, then backtracking when it fails.

**Comment by BBasile** [comment]
This bug should be of the highest priority, it actually causes much trouble in the tools based on dparse.
