### ISSUE TITLE
Parsing type expressions involving array indexing is broken

### ISSUE THREAD

**Issue by EyalIO** [dlang-community/libdparse#158]
T[1].X y;

Parses/formats back into: ".X y"

The Type/Type2+TypeSuffixes  seems to assume that if it parsed "[1]" it must mean array-of-1, and then mis-handles the ".X" which follows.

There's a fundamental ambiguity here between ordinary expressions yielding types, and type-exprs involving array decls - that is not quite handled correctly by libdparse.

**Comment by BBasile** [comment]
Actually it was not handled at all. This is the last case of an [IdentifierList](https://dlang.org/spec/grammar.html#IdentifierList) while dparse only handles [BasicType2X](https://dlang.org/spec/grammar.html#BasicType2X) named as TypeSuffix.
