### ISSUE TITLE
Test the parser with token strings rather than files

### ISSUE THREAD

**Issue by BBasile** [dlang-community/libdparse#187]
The tests in the pass / fail [folders](https://github.com/dlang-community/libdparse/tree/master/test) could be located in the sources. I do this in [Yatol](https://github.com/BBasile/yatol/blob/master/src/yatol/parser.d#L3800), and it's better since you can easily make a command to run the tests of a single file and see the coverage immediatly.

Actually i see no reasons to test dparse with external files.

**Comment by wilzbach** [comment]
Agreed. Maybe @Hackerpilot had a reason?

**Comment by Hackerpilot** [comment]
It might have been that it was easier to make small edits to the test files so that I could find specific problems with the parser without recompiling. They don't actually need to be separate.
