### ISSUE TITLE
Add precise source locations (start and end) to each ASTNode

### ISSUE THREAD

**Issue by aneas** [dlang-community/libdparse#191]
Many tools depend on having the source range of syntax nodes accessible. "Peek definition" popups in IDEs need them to avoid guessing. Refactoring operations need them to avoid destroying the code layout.

While there are no current tools profiting from this that I know of, adding this feature would open up new possibilities.

**Comment by timotheecour** [comment]
this blocks things like https://issues.dlang.org/show_bug.cgi?id=18488

**Comment by wilzbach** [comment]
> this blocks things like https://issues.dlang.org/show_bug.cgi?id=18488

For reference, it doesn't and I just closed the issue as INVALID).

> While there are no current tools profiting from this that I know of, adding this feature would open up new possibilities.

Almost all tokens already come with `index`, `column` and `line`. 
See https://github.com/dlang-community/libdparse/blob/master/src/std/experimental/lexer.d#L292

The `end` is a bit tricky, but typically is `.index` of the next sibling. Is this issue just about having `end` at every node?

**Comment by wilzbach** [comment]
BTW what's wrong with `startLocation` and `endLocation`? Did you simply not know about these attributes?

**Comment by BBasile** [comment]
Line and column (and index, i.e the byte position) are available for any declaration. Statements and expressions don't have this info. That being said, this is not done in a proper way. In the past there's been several PR to add location info (#55, #91, #97, #117, #118)  here and there while "we" should have put this in an ancestor node.

**Comment by timotheecour** [comment]
@wilzbach 

> BTW what's wrong with startLocation and endLocation? Did you simply not know about these attributes?

```
    override void visit(const ConditionalDeclaration decl){
       // if decl is unittest
        auto text = cast(immutable(char)[]) sourceCode[decl.startLocation.. decl.endLocation];
        import std.stdio;
        writeln(text);
    }
```
Error: no property startLocation for type const(ConditionalDeclaration)

**Comment by BBasile** [comment]
How about adding 2 virtual methods ? There are many cases where a token (which contains this information can be used so not each done needs to see its size increased by 16 bytes). I was thinking to this solution today because for example `AtAttribute` doesn't have line/col but its `.identifier` gives the info. Virtual methods would give an unified interface, without taking care of the results origin.
