### ISSUE TITLE
could libdparse reuse the newly developped dmd frontend?

### ISSUE THREAD

**Issue by timotheecour** [dlang-community/libdparse#192]
cf forum:"DMD as a library package can now run through all semantic phases"

**Comment by BBasile** [comment]
The question more: can DMDFE as a library replace dparse and dsymbol.

DMDFE memory management is done like for a compiler IIRC, meaning things are allocated but never freed. dparse, dsymbol are managed so that DCD can run for several days without going out of memory.
Also the AST is different.

**Comment by wilzbach** [comment]
The DMD dub package uses the GC for all allocations (or at least it's supposed to).
However, there is still a bit of work necessary to make the dmd frontend conveniently usable for humans.

There is an advantage of translating the AST from libdparse to dmd's frontend as existing tools will continue to work, but I don't know how hard this will be and how performant it will be. Essentially you would need to convert the AST to dmd's one, run the full semantics phase, and then convert it back again.

**Comment by wilzbach** [comment]
Of course for an initial, small experiment you could serialize to string in both cases and simply don't care about reparsing the AST twice.
