### ISSUE TITLE
Support for DIP1009 (new contracts syntax)

### ISSUE THREAD

**Issue by BBasile** [dlang-community/libdparse#218]
See https://github.com/dlang/DIPs/blob/master/DIPs/accepted/DIP1009.md#grammar.
No an emergency since it's not yet implemented so not used at all.

**Comment by BBasile** [comment]
well this is an emergency now...

**Comment by ZombineDev** [comment]
@wilzbach time to add "Needs libdparse PR" label to the dmd repo? IMO these types of changes are actual breaking changes for the ecosystem.

**Comment by wilzbach** [comment]
> time to add "Needs libdparse PR" label to the dmd repo? IMO these types of changes are actual breaking changes for the ecosystem.

Probably a good idea, but not sure whether other people will like it too.
If libdparse could parse all compilable and runnable files in the testsuite we could simply add the newest version of libdparse to the testsuite, but I guess that's a long-term dream...
