### ISSUE TITLE
Auto generation of the grammar doesn't work correctly

### ISSUE THREAD

**Issue by BBasile** [dlang-community/libdparse#251]
latest changes to contracts are not in the auto generated HTML (and some other older changes still not).

**Comment by BBasile** [comment]
That must be a GH bug, e.g rebuilding the site is not triggered because content pushed by travisCI is well the most up to date.

**Comment by wilzbach** [comment]
Yes I have written them twice and they always told me that it's a bug and "there team is aware of it".
Probably the easiest is to switch to Netlify, but I'm currently sick in bed. Will get to it on the weekend ;/

**Comment by BBasile** [comment]
Ah you should have said this ealier. For now i've found that to disable/re enable GH pages forces the regeneration, which is acceptable considering how often the DDOC is changed.

**Comment by wilzbach** [comment]
Fixed by https://github.com/dlang-community/libdparse/pull/259
