### ISSUE TITLE
libdparse fails parsing `alias foo = this`

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/libdparse#258]
Found in `func.d` at dmd.
Minimized:

```d
class F {
    bool equals()
    {
        alias fd1 = this;
    }
}
```

**Comment by BBasile** [comment]
It's because this as a type has been removed in #250. Specs say that

> Type aliases can sometimes look indistinguishable from alias declarations:
> The distinction is made in the semantic analysis pass.

So i suppose the commit should be reverted. The idea here is then that `this` will alias to the instance, always, and never to `typeof(this)`

**Comment by BBasile** [comment]
No actually i see now that the PR was not merged.
