### ISSUE TITLE
Inconsistencies of IfStatement conditions

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/libdparse#289]
I was testing the following cases using `ASTVisitor` and looking at the AST produced for the condition between parens:
```d
if (auto i = 1) {} // 1
if (const i = 1) {} // 2
if (int i = 1) {} // 3
if (const int i = 1) {} // 4
if (const(int) i = 1) {} // 5
```
The first thing is: unlike the others, condition `2` is parsed as an `AssignExpression`, meaning that the resulting `IfStatement.identifier` will not contain the identifier, and `IfStatement.expression` contains everything instead.

The second thing is: `3` and `4` will produce exactly the same result. The `const` qualifier will not be taken into account, since there is currently no property holding type constructors in `IfStatement`.
I don't know what the best way to resolve this would be; maybe simply adding `IdType[] typeConstructors` to `IfStatement`, like with `ForeachType`, would be sufficient ?

Both of these can be verified quickly using `dscanner --ast`.

**Comment by BBasile** [comment]
Yes, the best evidence is that DCD completion doesn't work for `i.` in case 2 (while it does always in the other cases).
