### ISSUE TITLE
Implement DIP1009 correctly

### ISSUE THREAD

**Issue by BBasile** [dlang-community/libdparse#303]
Meaning without lowering. See official grammar.

**Comment by BBasile** [comment]
Maybe @LaurentTreguier you would agree to do it ? I remember that you didn't like current implementation when you have worked on DFMT last month.
Otherwise anyone else you want to just connect to GH and put yourself as Assignee. Would be great if done before the 9 of November.

**Comment by LaurentTreguier** [comment]
I'll have a look and see what can be done.
If I understand correctly (sometimes, I don't), you're talking about parsing expression-based contracts as their own constructs and not transforming them into `InStatement`s and `OutStatement`s as it's currently done ?

**Comment by BBasile** [comment]
yes, correct DIP 1009 would be some thing like that.
