### ISSUE TITLE
v0.10.13 break compatibility with previous versions (`volatile` keyword removal)

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/libdparse#344]
For example, DFMT uses libdparse v0.10.x, but when trying to build with libdparse v0.10.13, a static assertion fails:
`Error: static assert:  "Invalid token: volatile"` because of https://github.com/dlang-community/libdparse/commit/e1a3e75f42436110a609ff15aeb4503e376e6c4c.
Since DFMT doesn't have a commited `dub.selections.json`, currently `dub fetch dfmt` + `dub run dfmt` can show this error if a system has never fetched DFMT previously.

**Comment by BBasile** [comment]
Sorry I forgot about this commit. I just have deleted the tag and released v0.11.0 instead. Situation should back to normal in about 1 hour.

**Comment by BBasile** [comment]
The service is surprisingly slow at detecting the change. Two hours is unusual.

**Comment by LaurentTreguier** [comment]
This is not the first time; it didn't pick up dub v1.13.0 even after multiple days, I believe it was only updated manually after I pointed it out. There seems to be a bug in the dub registry or something

**Comment by BBasile** [comment]
Lately i have deleted tags and it was detected fast.

**Comment by BBasile** [comment]
Maybe it needs another package to have a new tag ? I've pushed a tag elsewhere in case of.

**Comment by BBasile** [comment]
@LaurentTreguier, I think that the DUB website bug is be confirmed. The tag for the other stuff is detected now.

**Comment by BBasile** [comment]
And dparse tags are still not updated.
