### ISSUE TITLE
Syntax error on templatized variable declarations

### ISSUE THREAD

**Issue by andy-hanson** [dlang-community/libdparse#353]
```d
import std.stdio : writeln;

immutable int twice(int x) = 2 * x;

void main() {
	writeln(twice!5);
}
```

`dscanner --syntaxCheck source` fails with:
```
source/app.d(3:28)[error]: Expected `{` instead of `=`
```

**Comment by Basile-z** [comment]
The parser takes the way of parsing a function in this case. A lookup is needed to really make the difference.

**Comment by Basile-z** [comment]
fixed, but this will take some time to get ported to D-Scanner. I must wait dmd 2.087 to be released, then release a new minor version of dparse. If it's **really** necessary I can backport it to a dparse 0.11.z and 0.12.z branch though (D-Scanner still use 0.11 I think).

**Comment by Basile-z** [comment]
I've made the back port branch. I'm curious to see if this will works. It should if you build with dub, I think.
