### ISSUE TITLE
Memory usage - worst case file example

### ISSUE THREAD

**Issue by kiith-sa** [dlang-community/libdparse#36]
While testing my fork of harbored on various projects, I noticed huge memory usage with Tango in particular. I tracked it down to [this file](https://github.com/SiegeLord/Tango-D2/blob/d2port/tango/text/UnicodeData.d) - the file is unusually big (~600kiB), but the parser allocates ~222 MiB of memory, which still seems like a lot (passed an allocator to measure it).

This is not really a pressing issue (everyone has >=4GiB nowadays), just thought it may be useful for optimization.

**Comment by BBasile** [comment]
this is like #147, which is more detailed.
