### ISSUE TITLE
Error reported when parsing a DMD source file (backend/ptrntab.d)

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang-community/libdparse#372]
I noticed this after seeing D-Scanner parse `src/dmd/backend/ptrntab.d` in DMD's source tree.
Starting from 4c0e52133f8d7ba5de2099be673c821fac04cd7a, this file suddenly becomes full of errors when scanning it.
The first reported error is [at line 4794](https://github.com/dlang/dmd/blob/ed9025c1bb01ae003a7be6f15d6e2e2354d0b9d9/src/dmd/backend/ptrntab.d#L4794), with supposedly a missing parenthesis.

Tested on Linux x86_64, compiling using DMD 2.089.0 and the distro's LDC 1.15.0, with DMD's 2.089.0 source.

**Comment by MoonlightSentinel** [comment]
Fix #374
