### ISSUE TITLE
UDA supported?

### ISSUE THREAD

**Issue by andre2007** [dlang-community/libdparse#373]
In the documentation [https://libdparse.dlang.io/dparse/ast.html](https://libdparse.dlang.io/dparse/ast.html) I cannot find any information whether and how UDA are supported.

I would look to scan source code files and find e.g. classes which have a specific UDA assigned. Is this possible with libdparse?

**Comment by PetarKirov** [comment]
As an example, see: https://github.com/dlang/tools/blob/69a119f85a773339f539b98a12f25904008c4268/tests_extractor.d#L89

**Comment by andre2007** [comment]
Thank you so much.
