### ISSUE TITLE
Formatting AST including `@trusted` delegate produces invalid output

### ISSUE THREAD

**Issue by Geod24** [dlang-community/libdparse#383]
TL;DR: Test case for `formatter.d`:
```D
testFormatNode!(AssertExpression)("static assert(() @trusted { return bar()(3); }() == 4);");
```

Was trying to update libdparse for dlang.org (https://github.com/dlang/dlang.org/pull/2758) and hit this bug.
The code:
```D
 assert(() @trusted { return bar()(3); }() == 4);
```
from [here](https://github.com/dlang/phobos/blob/46525f7b3a61b820f71082e124dc684002e889f1/std/format.d#L2153) is turned into:
```D
assert (() @trusteddo
{ return bar()(3);
}() == 4)
```
by formatter, which is obviously invalid.

**Comment by WebFreak001** [comment]
related to #346

**Comment by Geod24** [comment]
Fixed by https://github.com/dlang-community/libdparse/pull/399

**Comment by WebFreak001** [comment]
@Geod24 fyi you can link pull requests in issues (and link issues in pull requests) to automatically close them with a reference: 
![popup showing when clicking on linked pull requests](https://user-images.githubusercontent.com/2035977/82181110-30624980-98e2-11ea-8344-fd411542c9b5.png)

**Comment by Geod24** [comment]
I don't have that kind of power in `dlang-community` ;)
