### ISSUE TITLE
Empty declaration for is(... == module)

### ISSUE THREAD

**Issue by MoonlightSentinel** [dlang-community/libdparse#395]
As found in DRuntimes `src/core/internal/execinfo.d`:
```
enum bool hasExecinfo = is(_execinfo == module);
```

```
src/core/internal/execinfo.d(71:25)[error]: Declaration expected
src/core/internal/execinfo.d(71:48)[warn]: Empty declaration
```

**Comment by WebFreak001** [comment]
the parseTypeSpecialization is outdated:

code: https://github.com/dlang-community/libdparse/blob/f327ce178ec447b7e5fe9247f911bc3f1bc12cd6/src/dparse/parser.d#L6985-L7041
reference: https://dlang.org/spec/grammar.html#IsExpression

missing:
- `__vector`
- `module`
- `package`

deprecated/removed:
- `typedef`
