### ISSUE TITLE
extern(C++, ...) only supports identifiers

### ISSUE THREAD

**Issue by MoonlightSentinel** [dlang-community/libdparse#397]
The following declarations are rejected by libdparse: 

```
enum abc = "abc";
__gshared:

extern(C++, "abc") int k;
extern(C++, "a", "b", "c") int m;
extern(C++, (abc)) int n;
extern(C++, ("abc")) int o;
```

(Allthough some of them aren't even documented in the spec)

**Comment by WebFreak001** [comment]
what isn't in the spec should also be reported to D

**Comment by WebFreak001** [comment]
```
onlineapp.d(3): Error: undefined identifier abc
```

**Comment by MoonlightSentinel** [comment]
> what isn't in the spec should also be reported to D

Gonna do that and maybe fix it along the way.



> ```
> onlineapp.d(3): Error: undefined identifier abc
> ```

Made the example compilable.

**Comment by WebFreak001** [comment]
actually all of your reported code here is wrong according to the spec: https://dlang.org/spec/attribute.html#linkage

Only identifier lists are allowed, never strings

**Comment by MoonlightSentinel** [comment]
`extern(C++, <string>)` is definitly under-documented but has it's use-cases.

**Comment by MoonlightSentinel** [comment]
I think it was intended as a more flexible alternative to an identifier, so  `extern(C++, "Foo.Bar")` should be identical to `extern(C++, Foo.Bar)` (but there are some quirks IIRC). See e.g. the [C++ bindings in Druntime](https://github.com/dlang/druntime/blob/10a6ec1620d189302e2949ef47b76fc7bb5decec/src/core/stdcpp/allocator.d#L15-L17)  for a practical example.

[DMD code](https://github.com/dlang/dmd/blob/00b5ad755eaf5de93e3c418c41da69add8a266a3/src/dmd/parse.d#L2245-L2256)

**Comment by Geod24** [comment]
Any serious user of C++ bindings is going to use `extern(C++, string-or-CTFEable)`, not the `extern(C++, identifier)` feature. But yeah it is very under-documented, both in the spec and in cpp_interface page.

**Comment by WebFreak001** [comment]
can someone explain what it even does with strings? I didn't really look a lot but where I looked I couldn't find any information

**Comment by Geod24** [comment]
Short answer:
- Can use any identifier, even those that are reserved in D;
- Cannot express `a::b`, it needs to be `extern(C++, "a") { extern(C++, "b") { ... } }`
- Unlike the identifier version, does *not* create a scope. That was actually the main point for it.
- CTFE-able;
- It's an identifier by default, so anything that could be interpreted as an identifier needs to be surrounded by parenthesis to disambiguate.

You can get a succinct view of the current implementation here: https://github.com/dlang/dmd/commit/fd8a8244fba7d7f7d5c51365ae9768bbb6f505a6

**Comment by MoonlightSentinel** [comment]
> * Cannot express `a::b`, it needs to be `extern(C++, "a") { extern(C++, "b") { ... } }`

Wait, what does `extern(C++, "a", "b")` do?

**Comment by Geod24** [comment]
Right, that was an (incomplete) response to:

> so `extern(C++, "Foo.Bar")` should be identical to `extern(C++, Foo.Bar)`

`extern(C++, "Foo.Bar")` should error out, and one should use `extern(C++, "Foo", "Bar")` instead.

**Comment by Geod24** [comment]
Thanks, I'll try to get the spec PR merged when we figure out why it's not passing...
