### ISSUE TITLE
spurious parse error with static foreach and mixin

### ISSUE THREAD

**Issue by NilsLankila** [dlang-community/libdparse#430]
```
static foreach (char c; "ABCDEFGHIJKLMN")
{
    mixin ("alias ", c, "(T) = T;");
    mixin ("alias ", c, c, " = ", c, "!int;");
}
```

> Declaration expected

**Comment by Hackerpilot** [comment]
I'm not able to reproduce the issue with the code snippet that you provided.

**Comment by NilsLankila** [comment]
it's possible that actually it would be fixed as dparse used is at 24155ce1b3514fe2db74a00260cf4bb17e77cef3

**Comment by Hackerpilot** [comment]
What tool were you using when you found this?

**Comment by NilsLankila** [comment]
I think this is indeed a problem whith the tool.
