### ISSUE TITLE
Buildkite CI was broken by v0.16.0

### ISSUE THREAD

**Issue by Geod24** [dlang-community/libdparse#431]
New tag, new Buildkite failure: https://buildkite.com/dlang/dmd/builds/14989

**Comment by Hackerpilot** [comment]
I think that this is caused by the new testing system requiring that libxml2-utils be installed.

**Comment by Hackerpilot** [comment]
It doesn't seem that there is a configuration file for Buildkite in this repository, so I'm not sure that I'm even able to fix this. I'll take another look in a few hours. It's very late in my time zone.

**Comment by Geod24** [comment]
By default, Buildkite will use the Travis script. However, since the environment it runs in is not containerized, it will only runs the test part, not the install part.
The simplest way would be to introduce an env variable so that some tests get skipped if run under Buildkite.
I'll disable libdparse in the meantime.

**Comment by Hackerpilot** [comment]
The tests in question are now skipped if the test detects the `BUILDKITE` environment variable, so this should be resolved.
