### ISSUE TITLE
Migrate stdx.allocator to std.experimental instead?

### ISSUE THREAD

**Issue by nordlow** [dlang-community/libdparse#447]
https://github.com/dlang-community/stdx-allocator hasn't been modified for 2 years.

Should libdparse, dsymbol and dscanner move to the more recently updated `std.experimental.allocator`?

If there's a consensus I can do the migration.

FYI, @RazvanN7

**Comment by JohanEngelen** [comment]
+1

To avoid silent regression, libdparse should be added to the dlang community tester (if it is not already on that list).

**Comment by nordlow** [comment]
So, shall I do the bump?

**Comment by nordlow** [comment]
See https://github.com/dlang-community/libdparse/pull/463.
