### ISSUE TITLE
Parses Ddoc file but shouldn't

### ISSUE THREAD

**Issue by rikkimax** [dlang-community/libdparse#448]
https://dlang.org/spec/ddoc.html#using_ddoc_for_other_documentation

If first token is "Ddoc", then it should not be treated as D code.

This is a problem for some files like this one: https://github.com/dlang/phobos/blob/master/index.d

**Comment by WebFreak001** [comment]
I don't think we want to support this and phobos also changed to .dd, which is a much more reasonable file extension for ddoc.
