### ISSUE TITLE
Libdparse parseModule reentrant

### ISSUE THREAD

**Issue by jaapgeurts** [dlang-community/libdparse#450]
I'm not sure where to ask this question because I can't find a forum or IRC channel for libdparse. Feel free to close/delete this issue if in error.

I've been trying to use libdparse in a project with threads (kdevelop background parsing). It keeps crashing when using multiple threads and what appears to be memory corruption. This seems to happen when the GC kicks in (either manually or automatically. If I disable the GC altogether it works just fine.) However running as a single thread and enabling the GC gives no issues. After analysing log output I suspect libdparse is giving issues.

Q: Is libdparse or the RollBackAllocator (and its dependencies) reentrant? If so, then I'll keep looking elsewhere. Otherwise I'll try to debug my code and possibly / libdparse.

Thank you.
Edit: typos.

**Comment by PetarKirov** [comment]
Thanks for raising this issue. I think we can enable the discussions feature on the repo and there would be more appropriate place to ask, but I see no harm in asking here, of course.

> Q: Is libdparse or the RollBackAllocator (and its dependencies) reentrant?

How do you define reentrant? Or do you mean thread-safe?

In a single threaded environment, reentrancy is usually about a library calling a user-defined callback and whether the code inside the callback is allowed to call the library. E.g.

    library A -> callback -> library A

If the question is about thread safety, I'd say that unless you see method explicitly marked as `shared`, then it's likely not thread-safe.

**Comment by WebFreak001** [comment]
there were fixes in the latest release of libdparse about the rollback allocator and GC breakage, but it's already release since quite a while ago so I would assume you already have it installed (v0.18.1)

**Comment by jaapgeurts** [comment]
> How do you define reentrant? Or do you mean thread-safe?

Yes, I did mean thread safe.

> I would assume you already have it installed (v0.18.1)

I do. I'm using the master branch as my dependency( which is 0.18.1)

I'll see if I can do some debugging on my end. Thanks for the help!

**Comment by WebFreak001** [comment]
It's probably not save using the same rollback allocator across multiple threads.

Having an allocator per thread should be safe, assuming the underlying Mallocator.instance it is using is thread-safe

**Comment by jaapgeurts** [comment]
It all seems thread-safe. The D docs state that Mallocator is thread safe. I'll keep debugging.

**Comment by jaapgeurts** [comment]
I found the problem. The StringCache went out of scope too early. Holding on to it fixed the problem. Right now libdparse is running fine in multiple threads. No more memory issues.
