### ISSUE TITLE
Follow 1215

### ISSUE THREAD

**Issue by Hackerpilot** [dlang-community/libdparse#46]
https://issues.dlang.org/show_bug.cgi?id=1215
https://github.com/D-Programming-Language/dmd/pull/4516

**Comment by mathias-lang-sociomantic** [comment]
This was fixed (there was a follow up P.R.: https://github.com/D-Programming-Language/dmd/pull/4918 ).

**Comment by Hackerpilot** [comment]
Related: http://forum.dlang.org/thread/oaqifnqictfdaupaaptn@forum.dlang.org

**Comment by BBasile** [comment]
This works since a while:

```
template Foo(T...)
{
    alias MyType = T[0].TheType;
}

template P(T)
{
    alias TheType = T;
}

void main()
{
    Foo!(P!int).MyType i = 0;
}
```

And dparse parses the "indexer" since a few week
