### ISSUE TITLE
Outdated gramar

### ISSUE THREAD

**Issue by etienne02** [dlang-community/libdparse#461]
https://libdparse.dlang.io/grammar.html and ddoc in parser are a bit outdated.
For example AliasAssign and StaticForeachDeclaration are supported by the parser but does not appear in the grammar

**Comment by maxhaton** [comment]
I think it's a casualty of travis ci dying

**Comment by WebFreak001** [comment]
temporary link: https://dlang-community.github.io/libdparse/grammar.html

the libdparse.dlang.io domain will be fixed soon to point to that page
