### ISSUE TITLE
Fix multi-array parsing

### ISSUE THREAD

**Issue by etienne02** [dlang-community/libdparse#479]
Currently the parser does not follow the specs for multi-dimensional array (https://dlang.org/spec/grammar.html#ArrayLiteral)
Example that should be parsed correctly:
```D
private void failure()
{
    static struct A
    {
        int a, b, c;
    }
    A [2][2] tests = [
        [ {1, 2, 3}, {}],
        [ {1}, ]
    ];
}
```
See https://github.com/intellij-dlanguage/intellij-dlanguage/issues/821

**Comment by WebFreak001** [comment]
seems to be parsed correctly, can't reproduce the issue

AST looks correct, DCD gives proper auto-completion
