### ISSUE TITLE
New release needed for dmd PR

### ISSUE THREAD

**Issue by ntrel** [dlang-community/libdparse#519]
Hi,
Is it possible to tag a new release soon please, that contains this merged pull?:
https://github.com/dlang-community/libdparse/pull/514

The phobos buildkite test depends on a release of libdparse:
https://github.com/dlang/dmd/pull/16315#issuecomment-2024195206

Thanks!

**Comment by WebFreak001** [comment]
done

**Comment by ntrel** [comment]
Thanks!
