### ISSUE TITLE
a few errors when using this from Dscanner

### ISSUE THREAD

**Issue by timotheecour** [dlang-community/libdparse#60]
- after updating libdparse 'manually' in Dscanner and changing the makefile with https://github.com/Hackerpilot/Dscanner/pull/279 to avoid the compile errors, I get:
  Warning: statement is not reachable
  (repeated tons of times)
  which is actually an error because of '-w'.

(I filed https://issues.dlang.org/show_bug.cgi?id=14905 to avoid repeating such warning messages in dmd in a reduced case, but regardless, this warning-as-error needs to be addressed)

=> sent out https://github.com/burner/inifiled/pull/4 for this which removes 'return false' from the 2 offending lines.

Also: 
- isn't 'Makefile' more standard than 'makefile' ? (Dscanner)
- would it be better to use libdparse as a library to make it easier to integrate in parent projects such as Dscanner ? (ie would avoid changing the makefile as done in https://github.com/Hackerpilot/Dscanner/pull/279)

**Comment by BBasile** [comment]
Seems to be old stuff, not valid anymore. Reopen if necessary.
