### ISSUE TITLE
fails for alias with FuncDeclarator

### ISSUE THREAD

**Issue by wilzbach** [dlang-community/libdparse#98]
libdparse fails to read such code properly, e.g:

```
alias int F1();
```

For more example see [typecons.d](https://github.com/dlang/phobos/blob/master/std/typecons.d#L4498).

According to the [D spec](https://dlang.org/spec/declaration.html#AliasDeclaration) that's valid code:

```
alias StorageClassesopt BasicType FuncDeclarator ;
```

Btw I would prefer to see the D Language changed in favor of accepting `alias F1 = int()`.

**Comment by Hackerpilot** [comment]
This limitation is in the README.

**Comment by wilzbach** [comment]
> This limitation is in the README.

Oh I didn't see that :/
Anyhow this is the last blocking piece when running dscanner on Phobos, some ideas
1) change phobos
2) add support add libdparse
3) change the language e.g. `alias F1 = int()`

what do you think is the best way to move forward?

**Comment by BBasile** [comment]
You've done it wilzbach !
